In [8]:
import string
import random
import uuid
import pandas as pd

In [3]:
def random_string(N=7):
    s = ''.join(random.choices(string.ascii_lowercase, k=N))
    c = uuid.uuid4().hex[:8]
    return "_".join([s, c])

random_string()

'mjkrypu_cd8666d8'

In [4]:
S = 10
SUBS = [random_string() for _ in range(S)]
SUBS

['glgokzf_2c231d16',
 'dlpxgus_5788d326',
 'kwcgrts_46e9f18d',
 'pudakqp_929a5ca9',
 'dtmgyqn_3a0c0401',
 'bkayhlq_a4a61e20',
 'qwxwnsq_9a6b50ef',
 'otmjuvw_6736f002',
 'nyjpala_bf338b49',
 'ivkdgxy_0cd4c243']

In [7]:
APP_CODE = "pnoistor_feb2023"
CLASS = "CLASS"
COMNT = "comnt"
TYPE = "TYPE"

def get_file_name(sid):
    hs = uuid.uuid4().hex[:4]
    s = "-".join([APP_CODE, sid, CLASS, hs, COMNT])
    return s + f".{TYPE}"

get_file_name(SUBS[0])

'pnoistor_feb2023-glgokzf_2c231d16-CLASS-d318-comnt.TYPE'

In [13]:
df = pd.DataFrame({"sid": SUBS})
df["app_code"] = APP_CODE
df["c_LBA"] = "LBA"
df["c_VBA"] = "VBA"
df["c_PFT"] = "PFT"
df["c_META"] = "META"

df["c_bf"] = "before"
df["c_af"] = "after"

df["c_LU"] = "LU"
df["c_RU"] = "RU"
df["c_LL"] = "LL"
df["c_RL"] = "RL"

df["hs"] = [uuid.uuid4().hex[:4] for _ in range(S)]

df
df

,sid,app_code,c_LBA,c_VBA,c_PFT,c_META,c_bf,c_af,c_LU,c_RU,c_LL,c_RL,hs
0,glgokzf_2c231d16,pnoistor_feb2023,LBA,VBA,PFT,META,before,after,LU,RU,LL,RL,0a79
1,dlpxgus_5788d326,pnoistor_feb2023,LBA,VBA,PFT,META,before,after,LU,RU,LL,RL,34bc
2,kwcgrts_46e9f18d,pnoistor_feb2023,LBA,VBA,PFT,META,before,after,LU,RU,LL,RL,7436
3,pudakqp_929a5ca9,pnoistor_feb2023,LBA,VBA,PFT,META,before,after,LU,RU,LL,RL,e218
4,dtmgyqn_3a0c0401,pnoistor_feb2023,LBA,VBA,PFT,META,before,after,LU,RU,LL,RL,572b
5,bkayhlq_a4a61e20,pnoistor_feb2023,LBA,VBA,PFT,META,before,after,LU,RU,LL,RL,395b
6,qwxwnsq_9a6b50ef,pnoistor_feb2023,LBA,VBA,PFT,META,before,after,LU,RU,LL,RL,e1ea
7,otmjuvw_6736f002,pnoistor_feb2023,LBA,VBA,PFT,META,before,after,LU,RU,LL,RL,4d22
8,nyjpala_bf338b49,pnoistor_feb2023,LBA,VBA,PFT,META,before,after,LU,RU,LL,RL,d2a0
9,ivkdgxy_0cd4c243,pnoistor_feb2023,LBA,VBA,PFT,META,before,after,LU,RU,LL,RL,e4c6

In [49]:
file_names = [
    "pnoistor_feb2023-SID-META-HS-comnt.json",

    "pnoistor_feb2023-SID-LBA_before_LU-HS-comnt.wav",
    "pnoistor_feb2023-SID-LBA_before_RU-HS-comnt.wav",
    "pnoistor_feb2023-SID-LBA_before_LL-HS-comnt.wav",
    "pnoistor_feb2023-SID-LBA_before_RL-HS-comnt.wav",

    "pnoistor_feb2023-SID-LBA_after_LU-HS-comnt.wav",
    "pnoistor_feb2023-SID-LBA_after_RU-HS-comnt.wav",
    "pnoistor_feb2023-SID-LBA_after_LL-HS-comnt.wav",
    "pnoistor_feb2023-SID-LBA_after_RL-HS-comnt.wav",

    "pnoistor_feb2023-SID-VBA_before-HS-comnt.wav",
    "pnoistor_feb2023-SID-VBA_after-HS-comnt.wav",

    "pnoistor_feb2023-SID-PFT_before-HS-comnt.pdf",
    "pnoistor_feb2023-SID-PFT_after-HS-comnt.pdf",

    "pnoistor_feb2023-SID-LBA_before_LU-HS-comnt.txt",
    "pnoistor_feb2023-SID-LBA_before_RU-HS-comnt.txt",
    "pnoistor_feb2023-SID-LBA_before_LL-HS-comnt.txt",
    "pnoistor_feb2023-SID-LBA_before_RL-HS-comnt.txt",


    "pnoistor_feb2023-SID-LBA_after_LU-HS-comnt.txt",
    "pnoistor_feb2023-SID-LBA_after_RU-HS-comnt.txt",
    "pnoistor_feb2023-SID-LBA_after_LL-HS-comnt.txt",
    "pnoistor_feb2023-SID-LBA_after_RL-HS-comnt.txt",

    "pnoistor_feb2023-SID-VBA_before-HS-comnt.txt",
    "pnoistor_feb2023-SID-VBA_after-HS-comnt.txt",


    "pnoistor_feb2023-SID-PFT_after-HS-comnt.csv",
    "pnoistor_feb2023-SID-PFT_before-HS-comnt.csv",
]

In [20]:
file_names_df = pd.DataFrame([fn.split("-") for fn in file_names])
file_names_df.columns = ["app_code", "sid", "class", "hs", "ext"]
file_names_df

            app_code  sid          class  hs         ext
0   pnoistor_feb2023  SID           META  HS  comnt.json
1   pnoistor_feb2023  SID  LBA_before_LU  HS   comnt.wav
2   pnoistor_feb2023  SID  LBA_before_RU  HS   comnt.wav
3   pnoistor_feb2023  SID  LBA_before_LL  HS   comnt.wav
4   pnoistor_feb2023  SID  LBA_before_RL  HS   comnt.wav
5   pnoistor_feb2023  SID   LBA_after_LU  HS   comnt.wav
6   pnoistor_feb2023  SID   LBA_after_RU  HS   comnt.wav
7   pnoistor_feb2023  SID   LBA_after_LL  HS   comnt.wav
8   pnoistor_feb2023  SID   LBA_after_RL  HS   comnt.wav
9   pnoistor_feb2023  SID     VBA_before  HS   comnt.wav
10  pnoistor_feb2023  SID      VBA_after  HS   comnt.wav
11  pnoistor_feb2023  SID      PFT_after  HS   comnt.pdf
12  pnoistor_feb2023  SID     PFT_before  HS   comnt.pdf
13  pnoistor_feb2023  SID  LBA_before_LU  HS   comnt.txt
14  pnoistor_feb2023  SID  LBA_before_RU  HS   comnt.txt
15  pnoistor_feb2023  SID  LBA_before_LL  HS   comnt.txt
16  pnoistor_feb2023  SID  LBA_before_RL  HS   comnt.txt
17  pnoistor_feb2023  SID   LBA_after_LU  HS   comnt.txt
18  pnoistor_feb2023  SID   LBA_after_RU  HS   comnt.txt
19  pnoistor_feb2023  SID   LBA_after_LL  HS   comnt.txt
20  pnoistor_feb2023  SID   LBA_after_RL  HS   comnt.txt
21  pnoistor_feb2023  SID     VBA_before  HS   comnt.txt
22  pnoistor_feb2023  SID      VBA_after  HS   comnt.txt
23  pnoistor_feb2023  SID      PFT_after  HS   comnt.csv
24  pnoistor_feb2023  SID     PFT_before  HS   comnt.csv

In [128]:
import hashlib
import os

In [160]:
def create_anotes(filename, bb=False, n=1):
    VBA_labels = [  
        "aa", "ee", "uu", "oo", 
        "ii", "xx",  "ii", "xx", "ii", "xx", "ii", "xx", "ii", "xx", 
        "aa", "ee", "uu", "oo"
    ]

    VBA_labels_df = pd.DataFrame(VBA_labels, columns=["label"])

    VBA_labels_df["start"] = list(range(0, len(VBA_labels_df) * 2, 2))
    VBA_labels_df["start"] += 2.3
    VBA_labels_df["end"] = VBA_labels_df["start"] + 2

    def inc_df(n):
        _df = VBA_labels_df.copy()

        _df["start"] += n * 50
        _df["end"] += n * 50
        _bb = [{
                "start": _df["start"][0],
                "end": _df["end"][len(_df) - 1],
                "label": f"bb{n + 1}",
        }]
        _bb_df =  pd.DataFrame(_bb)

        _df = pd.concat([_df, _bb_df])

        return _df


    VBA_labels_full_df = pd.concat([inc_df(n)  for n in range(0, 4)])

    if bb:

        _bb = [{
                "start": 2.3,
                "end": 38.3,
                "label": f"bb{n}",
        }]

        VBA_labels_full_df =  pd.DataFrame(_bb)

    VBA_labels_full_df.to_csv(filename, columns=["start", "end", "label"], sep="\t", index=False)




    return VBA_labels_full_df

create_anotes("test.txt", bb=False, n=1)

   label  start    end
0     aa    2.3    4.3
1     ee    4.3    6.3
2     uu    6.3    8.3
3     oo    8.3   10.3
4     ii   10.3   12.3
..   ...    ...    ...
14    aa  180.3  182.3
15    ee  182.3  184.3
16    uu  184.3  186.3
17    oo  186.3  188.3
0    bb4  152.3  188.3

[76 rows x 3 columns]

In [161]:
def file_hash(seed):
    m = hashlib.md5()
    m.update(seed.encode('utf-8'))
    new_uuid = uuid.UUID(m.hexdigest())
    return new_uuid.hex[:4]

DATA = "DATA"
if (not os.path.exists(DATA)):
    os.mkdir(DATA)

def make_sub():
    _file_name_df = file_names_df.copy()

    sid = random_string()
    _file_name_df["sid"] = sid
    _file_name_df["hs"] = [file_hash(r["sid"] + r["class"]) for i, r in _file_name_df.iterrows() ]

    os.mkdir(f"{DATA}/{sid}")

    return _file_name_df

sub_files = make_sub()

for i, fn in sub_files.iterrows():
    fname = "-".join(fn.to_dict().values())

    sid =  fn["sid"]
    fpath = f"{DATA}/{sid}/{fname}"
    open(fpath, 'a').close()
    
    if (".txt" in fname):
        if ("VBA" in fname):
            create_anotes(fpath)
        if ("LBA" in fname):
            if("LU" in fname):
                create_anotes(fpath, bb=True, n=1)

            if("RU" in fname):
                create_anotes(fpath, bb=True, n=2)

            if("LL" in fname):
                create_anotes(fpath, bb=True, n=3)

            if("RL" in fname):
                create_anotes(fpath, bb=True, n=4)
            


    # break

In [126]:


create_anotes("subid.txt")